### ISSUE TITLE
Compare web3privacy databases

### ISSUE THREAD

**Issue by cryptomar1o** [web3privacy/explorer-data#18]
**Describe the issue**
Data source from web3privacy.info. Should be reviewed if all data exported correctly

**Info**
src/projects files index.yaml from with https://web3privacy.info/

**Expected behavior**
Everything presented at web3privacy.info is also in projects files index.yaml

**Comment by DeBelg** [comment]
This is being worked on, @ethanolo-eth is currently importing the remaining projects. As this is currently manual labour it will take time however is in progress.
