### ISSUE TITLE
Missing logos

### ISSUE THREAD

**Issue by cryptomar1o** [web3privacy/explorer-data#19]
**Describe the issue**
Logos of projects are missing

**Info**
Check missing logo.svg in projects

**Expected behavior**
Each project has logo.svg file

**Comment by DeBelg** [comment]
Adding the first issue label incase any new people would like to help us out on some minor things

**Comment by DeBelg** [comment]
https://github.com/web3privacy/explorer-data/issues/696

Is the same issue, closing this as to be able to keep the current issues accurate.
