### ISSUE TITLE
Add multiple categories parameter

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/explorer-data#610]
One project can be highlighted in a several categories (example: FHE, AI).

We need to have an update within 
- data schema https://github.com/web3privacy/explorer-data/tree/main/schema
- sync with Sample project (guide) https://github.com/web3privacy/explorer-data/blob/main/sample-project.yaml

**Comment by DeBelg** [comment]
## Status update:

I believe this is currently in progress with the upcoming category update as mentioned here  https://github.com/web3privacy/explorer-data/issues/712

Closing this issue to merge this into 1 issue
