### ISSUE TITLE
Enable basic scoring model

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/explorer-data#611]
We need to enable basic scoring to work.

So instead of 63% we will have variables to impact (MVP).

Where variables are here https://mirror.xyz/0x0f1F3DAf416B74DB3DE55Eb4D7513a80F4841073/90XEXa7AG_qc-VgYKs40i88xB1HF97gr1zqb-qvnif0

![2024-06-23 12 54 32](https://github.com/web3privacy/explorer-data/assets/116563801/82b0495a-a946-4efd-a2a0-59ada5e6e277)

From data points
- product readiness
- docs (yes/no)
- github (yes/no)
- team: anon / public
- audit: yes / no

Mind:
- we don't need to score accurately
- it's to facilitate scoring documentation
- start actively talk with people
- empower projects to share data (contribute to explorer)

**Comment by DeBelg** [comment]
This is currently implemented, additional upgrade on scoring model will be happening in the future as well.
