### ISSUE TITLE
Add sunset badge marking sunset projects

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/explorer-data#695]
Sunset icon will help to mark defunct projects (valuable for research) or giving the next life to them.

![Screenshot 2024-08-15 at 18 15 09](https://github.com/user-attachments/assets/192649e6-321d-4e96-8a11-fb443d7b2f94)

**Comment by DeBelg** [comment]
There will be a sunset tagline in the new schema, and those will eventually be filtered out into an individual "archive" category. Altho this is not yet planned for the next release.

<img width="1079" alt="Screenshot 2024-08-23 at 17 41 35" src="https://github.com/user-attachments/assets/17b3af54-e749-4353-99d6-2174f030725a">

**Comment by DeBelg** [comment]
## Status update

As the category update is happening, "sunset" will be part of "Archived Projects" Going to link this in the same issue regarding Category update to keep everything in the singular issue: 

https://github.com/web3privacy/explorer-data/issues/712

**Comment by DeBelg** [comment]
This is now happening, marking this as closed @Msiusko
