### ISSUE TITLE
Add all icons

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/explorer-data#696]
We still miss some icons - will be nice to have all icons for all the projects

![Screenshot 2024-08-15 at 18 10 39](https://github.com/user-attachments/assets/b4d219b6-480b-4ae7-bfd6-dbcdd83e8c97)

**Comment by Msiusko** [comment]
Missing logos here https://explorer.web3privacy.info/category/messaging

**Comment by DeBelg** [comment]
# Projects Missing logo.png

- justnote
- bringing-privacy-to-ens
- juno-analytics
- krebit
- brace
- Presearch
- damus
- liquidfactory
- privatixy
- oasiis-insights
- nocturne
- Codex
- DeGuard
- fade-wtf
- RawBox
- literully
- freechat
- definer
- mask
- buildoor
- oksign
- eth-privacy
- flock-io
- onion-mixer
- DeNet
- whirlpool
- Ritual
- fyeo-identity
- sahara
- burstlq
- yellow-submarine
- IVPN

@ethanolo-eth 

Also wrote a local script to check if logos are present or not incase anyone wants to repeat this in the future;


`import os

def find_missing_logos(root_dir):
    missing_logos = []
    
    for dirpath, dirnames, filenames in os.walk(root_dir):
        if "logo.png" not in filenames:
            # Extract only the project name (last part of the path)
            project_name = os.path.basename(dirpath)
            missing_logos.append(project_name)
    
    return missing_logos

def write_to_markdown(missing_logos, output_file):
    with open(output_file, 'w') as f:
        f.write("# Projects Missing logo.png\n\n")
        for project in missing_logos:
            f.write(f"- {project}\n")

if __name__ == "__main__":
    root_directory = "FILL IN YOUR DIRECTORY HERE"
    
    if not os.path.isdir(root_directory):
        print(f"Error: {root_directory} is not a valid directory")
        exit(1)
    
    missing_logos = find_missing_logos(root_directory)
    
    output_file = "missing_logos.md"
    write_to_markdown(missing_logos, output_file)
    
    print(f"Results have been written to {output_file}")
    print(f"Number of projects missing logo.png: {len(missing_logos)}")
`

**Comment by DeBelg** [comment]
[LogoLessFinderScript.py.zip](https://github.com/user-attachments/files/16918652/LogoLessFinderScript.py.zip)


Python script incase anyone needs to repeat this in the future ^

**Comment by ethanolo-eth** [comment]
I have added the missing logos. 
i have difficulty finding these last 5:

- oasiis insight
- fade wtf
- yellow submarine
- onion mixer
- whirlpool
