### ISSUE TITLE
Check duplicated projects

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/explorer-data#697]
Keep one that is more filled with the data

![Screenshot 2024-08-15 at 18 09 52](https://github.com/user-attachments/assets/dd98b758-316a-4ac1-b642-5f95eae51346)

**Comment by Msiusko** [comment]
Here are duplucated https://explorer.web3privacy.info/category/FHE

**Comment by DeBelg** [comment]
> Collaborator

Closing as mention of done by @ethanolo-eth
