### ISSUE TITLE
Cleaning categories and define Use-cases

### ISSUE THREAD

**Issue by coinmandeer** [web3privacy/explorer-data#735]
current state of research is in Figma: https://www.figma.com/design/VTpA25b5jTEkhciTwvcrth/W3PN---UI-%26-UX?node-id=340-7&t=5ig3TWEPiOHJvUZo-1

we are open to any ideas how to structure database, mostly reduce amount of categories and  find usecases for those categories

**Comment by DeBelg** [comment]
Finished this last week, has been given to the dev team as well for the upcoming update
